services:
    api:
        build:
            context: .docker/php
            dockerfile: Dockerfile
        depends_on:
            - postgres
        volumes:
            - ./:/var/www/html
            - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            app-network:
    nginx:
        image: nginx:1.25.3-alpine
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - "8000:8000"
            - "6001:6001"
        volumes:
            - ./:/var/www/html
            - .docker/nginx:/etc/nginx/conf.d
        networks:
            app-network:
    #Postgres Service
    postgres:
        image: postgres:alpine
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /data/postgres
        volumes:
            - postgres-data:/data/postgres
        ports:
            - '5432:5432'
        networks:
            app-network:
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - '${PGADMIN_PORT:-5050}:80'
        networks:
            app-network:
        restart: unless-stopped

networks:
    app-network:

volumes:
    app-data:
    postgres-data:
    pgadmin: